sonar.organization=terok-ai
sonar.projectKey=terok-ai_terok-dbus
sonar.sources=src
sonar.tests=tests
sonar.python.coverage.reportPaths=reports/coverage.xml
sonar.python.bandit.reportPaths=reports/bandit-report.json
sonar.python.ruff.reportPaths=reports/ruff-report.json
